name: Run R script and commit

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@master

    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies
      run: sudo apt-get install -y libcurl4-openssl-dev

    - name: Install dependencies
      run: |
        Rscript -e "install.packages('tidyr')"
        Rscript -e "install.packages('dplyr')"
        Rscript -e "install.packages('stringr')"
        Rscript -e "install.packages('readr')"
        Rscript -e "install.packages('rvest')"
        Rscript -e "install.packages('lubridate')"

    - name: Descargar encuestas
      run: Rscript descargar_encuestas.R

    - name: Commit and push if it changed
      run: |
        git diff
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Update data"
        git push
