name: Run R script and commit

on:
  schedule:
    # Run this workflow every day at midnight
    - cron:  '10 21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@master

    - name: Setup R
      uses: r-lib/actions/setup-r@master

    - name: Descargar encuestas
      run: |
        source("descargar_encuestas.R")
      shell: Rscript {0}

    - name: Commit and push if it changed
      run: |
        git diff
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Update data"
        git push
