name: Run R script and commit

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@master

    - name: Setup R
      uses: r-lib/actions/setup-r@master

    - name: Descargar encuestas
      run: Rscript descargar_encuestas.R

    - name: Commit and push if it changed
      run: |
        git diff
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Update data"
        git push
